Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Assignment.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Assignment.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Assignment.Services.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace Assignment.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly ICategoryService _categoryService;

        public ProductsController(IProductService productService, ICategoryService categoryService)
        {
            _productService = productService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index(int? categoryId)
        {
            var categories = await _categoryService.GetAllCategoriesAsync();
            ViewBag.Categories = categories;

            var products = categoryId.HasValue
                ? await _productService.GetProductsByCategoryAsync(categoryId.Value)
                : await _productService.GetAllProductsAsync();

            return View(products);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Pine Software</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Assignment.styles.css" asp-append-version="true"/>
</head>
<body>

<header id="banner" class="d-flex justify-content-between align-items-center p-3">
    <!-- Sol tarafta logo -->
    <div>
        <img src="~/images/PineSoftware.png" alt="Pine Software Logo" class="logo">
    </div>

    <!-- Sağ tarafta "Kayıt Ol" ve "Giriş Yap" butonları -->
    <div>
        <a asp-controller="Account" asp-action="Register" class="btn btn-light me-2">Kayıt Ol</a>
        <a asp-controller="Account" asp-action="Login" class="btn btn-outline-light">Giriş Yap</a>
    </div>
</header>

<!-- Navigasyon Menüsü -->
<nav>
    <ul>
        <li><a asp-controller="Home" asp-action="Index" class="menu-item">Anasayfa</a></li>
        <li><a asp-controller="About" asp-action="Index" class="menu-item">Hakkımızda</a></li>
        <li><a asp-controller="Projects" asp-action="Index" class="menu-item">Projelerimiz</a></li>
        <li><a asp-controller="Products" asp-action="Index" class="menu-item">Ürünler</a></li>
        <li><a asp-controller="Contact" asp-action="Index" class="menu-item">İletişim</a></li>
    </ul>
</nav>

<div>
    <main role="main" class="content-wrapper">
        @RenderBody()
    </main>
</div>

<footer>
    &copy; 2024 - Emir Safa Yavuz - <a href="https://maltepe.edu.tr" target="_blank">Maltepe University</a>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>